### ISSUE TITLE
text!./datepicker.css and text!./select2/select2.css not loading

### ISSUE THREAD

**Issue by jsmccrumb** [mediassarQlikBranch/SimpleFieldSelect#16]
Version 1.8.7 changed:
![image](https://user-images.githubusercontent.com/13281202/60587867-80d0c700-9d63-11e9-8fa0-e90cc369f5de.png)

but the others stayed as text. On latest version of Qliksense we are seeing .js appended to the ones with text! in front of them, perhaps this needs to be changed to css!

**Comment by mediassarQlikBranch** [comment]
THanks for the feedback. 
Those are on purpose marked as text so that they don't load into CSS content. They will be added later when/if needed. I didn't found issue with this approach with latest Qlik release I'm using (June 2019 I think). Please make another ticket if something is not working due this issue.
