### ISSUE TITLE
toggle switch and version question

### ISSUE THREAD

**Issue by hvdbunte** [mediassarQlikBranch/SimpleFieldSelect#21]
Hello,

Thanks for this nice extionsion. 
I have two questions. 

1. Would it be possible to add a toggle switch? for example to use with a variable to filter data? Or is that already possible? With the radio button I can select a 0 or 1, but I would like to use a toggle switch, that looks better in an app. 
We would like to use this to filter specific columns from a pivot table or filter specific data from a table. 
![image](https://user-images.githubusercontent.com/16244611/68297142-7a968280-0096-11ea-92d2-eff99b214b4f.png)

2. When I install the latest version of the extension, 1.9.22, I still see previous installed version number, for us 1.9.12, when opening an app on my client and another version number on the server, 1.9.18, in the about section. How can I check if the latest version is installed? 

We are using qlik sense April 2019 sp3 version. 

Kind regards,

 hvdbunte

**Comment by mediassarQlikBranch** [comment]
Hi

That Toggleswitch is implemented already. It is called Qlik Switch in the Visualization -selection. It is sometimes a little bit tricky visual.
The version number doesn't change allways because I just forget to change it to all places. :) Check changelog file in case you are not sure, it will be anyway updated.
